sudo: required
os: linux
dist: trusty
language: node_js
node_js:
  - "6.12"
env:
  global:
    - NODE_ENV=test
addons:
  apt:
    packages:
      # for composer
      - zip
before_install:
  - phpenv global 7.1
  - php -v
  - npm install -g yarn
install:
  - yarn install
script:
  - npm test
